#include "Settings/DocumentSettings.hpp"

#include <Arcane/Config/Settings.hpp>
#include <Arcane/Reflection.hpp>

namespace Arcane::Editor
{
    ARC_REFLECT_TYPE(EditorPreviewLightSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.preview.light", SettingScope::PreferencesMachine, ApplyMode::Live, Audience::Editor)
        ARC_REFLECT_FIELD(EditorPreviewLightSettings, direction)
            ARC_REFLECT_ATTR(DisplayName, "Light direction")
            ARC_REFLECT_ATTR(Keywords, "preview thumbnail material sphere mesh lighting")
            ARC_REFLECT_ATTR(Tooltip, "Direction TOWARD the one light of the material sphere, the Asset Browser's mesh and "
                                      "material thumbnails and the mesh document's preview (+Y up). Thumbnails already "
                                      "rendered keep their old lighting until they are re-harvested.")
        ARC_REFLECT_FIELD(EditorPreviewLightSettings, ambient)
            ARC_REFLECT_ATTR(DisplayName, "Ambient") ARC_REFLECT_ATTR(Range, 0.0, 1.0)
            ARC_REFLECT_ATTR(Tooltip, "Flat fill light on the preview meshes' unlit side (0 = black).")
        ARC_REFLECT_FIELD_NAMED(EditorPreviewLightSettings, color, "colour")   // frozen name editor.preview.light.colour (R1)
            ARC_REFLECT_ATTR(DisplayName, "Light color")
            ARC_REFLECT_ATTR(Tooltip, "Color of the preview light.")
    ARC_END_REFLECT_TYPE()

    ARC_REFLECT_TYPE(EditorPreviewSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.preview", SettingScope::PreferencesMachine, ApplyMode::Live, Audience::Editor)
        ARC_REFLECT_FIELD(EditorPreviewSettings, sphereRings)
            ARC_REFLECT_ATTR(DisplayName, "Sphere rings") ARC_REFLECT_ATTR(Category, "Material sphere")
            ARC_REFLECT_ATTR(Range, 3.0, 128.0) ARC_REFLECT_ATTR(Apply, ApplyMode::Restart) ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Pole-to-pole rings of the material preview sphere's mesh.")
        ARC_REFLECT_FIELD(EditorPreviewSettings, sphereSegments)
            ARC_REFLECT_ATTR(DisplayName, "Sphere segments") ARC_REFLECT_ATTR(Category, "Material sphere")
            ARC_REFLECT_ATTR(Range, 3.0, 128.0) ARC_REFLECT_ATTR(Apply, ApplyMode::Restart) ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Segments around the material preview sphere's equator.")
        ARC_REFLECT_FIELD(EditorPreviewSettings, sphereFov)
            ARC_REFLECT_ATTR(DisplayName, "Sphere field of view") ARC_REFLECT_ATTR(Category, "Material sphere")
            ARC_REFLECT_ATTR(Range, 10.0, 120.0)
            ARC_REFLECT_ATTR(Tooltip, "Vertical field of view, in degrees, of the camera on the material preview sphere "
                                      "(the shader editor's preview and the material thumbnails).")
    ARC_END_REFLECT_TYPE()

    ARC_REFLECT_TYPE(ShaderEditorSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.shader", SettingScope::PreferencesMachine, ApplyMode::Live, Audience::Editor)
        ARC_REFLECT_FIELD(ShaderEditorSettings, navHistoryMax)
            ARC_REFLECT_ATTR(DisplayName, "Navigation history") ARC_REFLECT_ATTR(Range, 1.0, 1024.0)
            ARC_REFLECT_ATTR(Keywords, "back forward views")
            ARC_REFLECT_ATTR(Tooltip, "How many view changes the shader editor's Back/Forward history keeps.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, previewResolution)
            ARC_REFLECT_ATTR(DisplayName, "Preview resolution") ARC_REFLECT_ATTR(Range, 64.0, 2048.0)
            ARC_REFLECT_ATTR(Apply, ApplyMode::Restart)
            ARC_REFLECT_ATTR(Tooltip, "Side, in pixels, of the shader editor's square material preview. A document reads it "
                                      "when it opens.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, renameListMax)
            ARC_REFLECT_ATTR(DisplayName, "Rename list length") ARC_REFLECT_ATTR(Range, 1.0, 100.0)
            ARC_REFLECT_ATTR(Tooltip, "How many affected instance files the Rename Param Everywhere dialog lists by name "
                                      "before it summarizes the rest.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, bodyPreviewLines)
            ARC_REFLECT_ATTR(DisplayName, "Custom body preview lines") ARC_REFLECT_ATTR(Range, 1.0, 64.0)
            ARC_REFLECT_ATTR(Tooltip, "How many lines of a Custom node's code its node body shows.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, bodyPreviewChars)
            ARC_REFLECT_ATTR(DisplayName, "Custom body preview width") ARC_REFLECT_ATTR(Range, 8.0, 256.0)
            ARC_REFLECT_ATTR(Tooltip, "How many characters of each Custom node code line its node body shows before \"...\".")
        ARC_REFLECT_FIELD(ShaderEditorSettings, previewCheckerCell)
            ARC_REFLECT_ATTR(DisplayName, "Preview checker cell") ARC_REFLECT_ATTR(Range, 4.0, 128.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Keywords, "checkerboard square size")
            ARC_REFLECT_ATTR(Tooltip, "Side, in preview pixels, of one square of the checkerboard behind the shader "
                                      "editor's preview.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, previewCheckerLight)
            ARC_REFLECT_ATTR(DisplayName, "Preview checker light squares") ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Keywords, "checkerboard thumbnail")
            ARC_REFLECT_ATTR(Tooltip, "Color of the light squares of the checkerboard behind the shader editor's preview "
                                      "and the material thumbnails.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, previewCheckerSpriteScale)
            ARC_REFLECT_ATTR(DisplayName, "Sprite preview size") ARC_REFLECT_ATTR(Range, 0.1, 1.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Keywords, "checkerboard thumbnail quad")
            ARC_REFLECT_ATTR(Tooltip, "How much of the preview a sprite material's quad covers, as a fraction of its side.")
        ARC_REFLECT_FIELD(ShaderEditorSettings, passThumbPx)
            ARC_REFLECT_ATTR(DisplayName, "Pass thumbnail size") ARC_REFLECT_ATTR(Range, 16.0, 512.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Side, in canvas units, of the live preview thumbnail on the pass chain's base node.")
    ARC_END_REFLECT_TYPE()

    ARC_REFLECT_TYPE(ShaderChainLayoutSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.shader.chainLayout", SettingScope::PreferencesMachine, ApplyMode::Live,
                              Audience::Editor)
        ARC_REFLECT_FIELD(ShaderChainLayoutSettings, originX)
            ARC_REFLECT_ATTR(DisplayName, "Base X") ARC_REFLECT_ATTR(Range, -100000.0, 100000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Canvas X of the base material node when a pass chain is laid out for the first time.")
        ARC_REFLECT_FIELD(ShaderChainLayoutSettings, originY)
            ARC_REFLECT_ATTR(DisplayName, "Base Y") ARC_REFLECT_ATTR(Range, -100000.0, 100000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Canvas Y of the base, pass and Output nodes when a pass chain is laid out for the "
                                      "first time.")
        ARC_REFLECT_FIELD(ShaderChainLayoutSettings, pitchX)
            ARC_REFLECT_ATTR(DisplayName, "Node pitch") ARC_REFLECT_ATTR(Range, 1.0, 10000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Canvas distance between consecutive nodes of a newly laid-out pass chain.")
        ARC_REFLECT_FIELD(ShaderChainLayoutSettings, sceneOffsetX)
            ARC_REFLECT_ATTR(DisplayName, "Scene source offset X") ARC_REFLECT_ATTR(Range, -10000.0, 10000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Canvas X offset of the Scene source from the base node (negative = to its left).")
        ARC_REFLECT_FIELD(ShaderChainLayoutSettings, sceneOffsetY)
            ARC_REFLECT_ATTR(DisplayName, "Scene source offset Y") ARC_REFLECT_ATTR(Range, -10000.0, 10000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Canvas Y offset of the Scene source from the base node (positive = below it).")
    ARC_END_REFLECT_TYPE()

    ARC_REFLECT_TYPE(MeshDocSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.mesh", SettingScope::PreferencesMachine, ApplyMode::Live, Audience::Editor)
        ARC_REFLECT_FIELD(MeshDocSettings, previewResolution)
            ARC_REFLECT_ATTR(DisplayName, "Preview resolution") ARC_REFLECT_ATTR(Category, "Preview")
            ARC_REFLECT_ATTR(Range, 64.0, 2048.0) ARC_REFLECT_ATTR(Apply, ApplyMode::Restart)
            ARC_REFLECT_ATTR(Tooltip, "Side, in pixels, of the mesh document's square preview. A document reads it when it opens.")
        ARC_REFLECT_FIELD(MeshDocSettings, previewFov)
            ARC_REFLECT_ATTR(DisplayName, "Preview field of view") ARC_REFLECT_ATTR(Category, "Preview")
            ARC_REFLECT_ATTR(Range, 10.0, 120.0)
            ARC_REFLECT_ATTR(Tooltip, "Vertical field of view, in degrees, of the mesh document's preview camera.")
        ARC_REFLECT_FIELD(MeshDocSettings, previewMargin)
            ARC_REFLECT_ATTR(DisplayName, "Preview framing margin") ARC_REFLECT_ATTR(Category, "Preview")
            ARC_REFLECT_ATTR(Range, 1.0, 4.0)
            ARC_REFLECT_ATTR(Tooltip, "How far back the mesh preview camera sits, as a multiple of the distance that just "
                                      "fits the mesh's bounding sphere (1 = touching the edges).")
        ARC_REFLECT_FIELD(MeshDocSettings, capsuleRatioDragSpeed)
            ARC_REFLECT_ATTR(DisplayName, "Capsule length ratio drag speed") ARC_REFLECT_ATTR(Category, "Authoring limits")
            ARC_REFLECT_ATTR(Range, 0.0001, 1.0) ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "How much a capsule's Length Ratio changes per pixel dragged.")
    ARC_END_REFLECT_TYPE()

    ARC_REFLECT_TYPE(EditorMeshPrimitiveRangesSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.mesh.primitiveRanges", SettingScope::PreferencesMachine, ApplyMode::Live,
                              Audience::Editor)
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, planeSubdivisionsMin)
            ARC_REFLECT_ATTR(DisplayName, "Plane subdivisions (min)") ARC_REFLECT_ATTR(Range, 1.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Smallest Subdivisions value the mesh document offers for a procedural plane (1 at least).")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, planeSubdivisionsMax)
            ARC_REFLECT_ATTR(DisplayName, "Plane subdivisions (max)") ARC_REFLECT_ATTR(Range, 1.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Largest Subdivisions value the mesh document offers for a procedural plane.")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, sphereRingsMin)
            ARC_REFLECT_ATTR(DisplayName, "Sphere rings (min)") ARC_REFLECT_ATTR(Range, 3.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Smallest Rings value the mesh document offers for a procedural UV sphere (3 at least).")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, sphereRingsMax)
            ARC_REFLECT_ATTR(DisplayName, "Sphere rings (max)") ARC_REFLECT_ATTR(Range, 3.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Largest Rings value the mesh document offers for a procedural UV sphere.")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, segmentsMin)
            ARC_REFLECT_ATTR(DisplayName, "Segments (min)") ARC_REFLECT_ATTR(Range, 3.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Smallest Segments value the mesh document offers for a procedural sphere, cylinder or capsule (3 at least).")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, segmentsMax)
            ARC_REFLECT_ATTR(DisplayName, "Segments (max)") ARC_REFLECT_ATTR(Range, 3.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Largest Segments value the mesh document offers for a procedural sphere, cylinder or capsule.")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, capsuleRingsMin)
            ARC_REFLECT_ATTR(DisplayName, "Capsule cap rings (min)") ARC_REFLECT_ATTR(Range, 2.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Smallest Rings value (per hemispherical cap) the mesh document offers for a procedural capsule (2 at least).")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, capsuleRingsMax)
            ARC_REFLECT_ATTR(DisplayName, "Capsule cap rings (max)") ARC_REFLECT_ATTR(Range, 2.0, 1024.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Largest Rings value (per hemispherical cap) the mesh document offers for a procedural capsule.")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, capsuleLengthRatioMin)
            ARC_REFLECT_ATTR(DisplayName, "Capsule length ratio (min)") ARC_REFLECT_ATTR(Range, 1.0, 1000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Smallest Length Ratio the mesh document offers for a procedural capsule (1 at least).")
        ARC_REFLECT_FIELD(EditorMeshPrimitiveRangesSettings, capsuleLengthRatioMax)
            ARC_REFLECT_ATTR(DisplayName, "Capsule length ratio (max)") ARC_REFLECT_ATTR(Range, 1.0, 1000.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Tooltip, "Largest Length Ratio the mesh document offers for a procedural capsule.")
    ARC_END_REFLECT_TYPE()

    ARC_REFLECT_TYPE(SpriteDocSettings)
        ARC_REFLECT_TYPE_ATTR(Settings, "editor.sprite", SettingScope::PreferencesMachine, ApplyMode::Live, Audience::Editor)
        ARC_REFLECT_FIELD(SpriteDocSettings, ppuDragSpeed)
            ARC_REFLECT_ATTR(DisplayName, "Pixels per meter drag speed") ARC_REFLECT_ATTR(Range, 0.001, 100.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Keywords, "ppu")
            ARC_REFLECT_ATTR(Tooltip, "How much a sprite's Pixels Per Meter changes per pixel dragged.")
        ARC_REFLECT_FIELD(SpriteDocSettings, ppuMin)
            ARC_REFLECT_ATTR(DisplayName, "Pixels per meter (min)") ARC_REFLECT_ATTR(Range, 0.001, 65536.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Keywords, "ppu")
            ARC_REFLECT_ATTR(Tooltip, "Smallest Pixels Per Meter the sprite document accepts.")
        ARC_REFLECT_FIELD(SpriteDocSettings, ppuMax)
            ARC_REFLECT_ATTR(DisplayName, "Pixels per meter (max)") ARC_REFLECT_ATTR(Range, 1.0, 65536.0)
            ARC_REFLECT_ATTR(Flags, CVarFlags::Dev)
            ARC_REFLECT_ATTR(Keywords, "ppu")
            ARC_REFLECT_ATTR(Tooltip, "Largest Pixels Per Meter the sprite document accepts.")
        ARC_REFLECT_FIELD(SpriteDocSettings, pivotDragSpeed)
            ARC_REFLECT_ATTR(DisplayName, "Pivot drag speed") ARC_REFLECT_ATTR(Range, 0.0001, 0.1)
            ARC_REFLECT_ATTR(Tooltip, "How much a sprite's normalized pivot changes per pixel dragged.")
    ARC_END_REFLECT_TYPE()

    ARC_SETTINGS(EditorPreviewLightSettings);
    ARC_SETTINGS(EditorPreviewSettings);
    ARC_SETTINGS(ShaderEditorSettings);
    ARC_SETTINGS(ShaderChainLayoutSettings);
    ARC_SETTINGS(MeshDocSettings);
    ARC_SETTINGS(EditorMeshPrimitiveRangesSettings);
    ARC_SETTINGS(SpriteDocSettings);
}
