name: Windows Build for Arcane Engine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Premake5
      - name: Install Premake5
        run: |
          Invoke-WebRequest -Uri https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -OutFile premake5.zip
          Expand-Archive -Path premake5.zip -DestinationPath premake5
          Copy-Item premake5\premake5.exe -Destination $Env:ProgramFiles\premake5

      # Step 3: Generate project files using Premake5
      - name: Generate Visual Studio Project
        run: |
          $Env:Path += ";$Env:ProgramFiles\premake5"
          premake5\premake5.exe vs2022

      # Step 4: Build in Debug configuration
      - name: Build Debug configuration
        run: |
          msbuild Arcane.sln /p:Configuration=Debug /m

      # Step 5: Build in Release configuration
      - name: Build Release configuration
        run: |
          msbuild Arcane.sln /p:Configuration=Release /m

      # Step 6: Run tests (if you have tests configured)
      - name: Run Tests (optional)
        run: |
          .\bin\Debug-windows-x64\ArcaneTest.exe

      # (Optional) Upload build artifacts for debugging
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: arcane-engine-artifacts
          path: |
            bin/Debug-windows-x64/
            bin/Release-windows-x64/
